" Generated by vim-plug
" 07-11-2022 09:05:44 PM
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['coc-fzf'].commit = '60828294b9ba846c78893389d4772021043d2fa1'
silent! let g:plugs['coc.nvim'].commit = '4ca6db5a5105b15a532edbf4f1388a6e34071ab2'
silent! let g:plugs['fzf'].commit = '5f385d88e0a786f20c4231b82f250945a6583a17'
silent! let g:plugs['fzf.vim'].commit = '1f7bfa4007043c30027b2cd79625e8aac5cff1f9'
silent! let g:plugs['gruvbox'].commit = 'bf2885a95efdad7bd5e4794dd0213917770d79b7'
silent! let g:plugs['nerdcommenter'].commit = 'f8671f783baeb0739f556d9b6c440ae1767340d6'
silent! let g:plugs['nerdtree'].commit = 'eed488b1cd1867bd25f19f90e10440c5cc7d6424'
silent! let g:plugs['nvim-colorizer.lua'].commit = '36c610a9717cc9ec426a07c8e6bf3b3abcb139d6'
silent! let g:plugs['nvim-treesitter'].commit = '8e51f78d09f53e1980e2e842267c5236d907b9c9'
silent! let g:plugs['nvim-treesitter-cpp-tools'].commit = '6c37990655440a77a114ad9a9e11e97959d0504d'
silent! let g:plugs['vim-airline'].commit = '2cea8346cfaf0d92da079c27708bec7c092cef84'
silent! let g:plugs['vim-airline-themes'].commit = '97cf3e6e638f936187d5f6e9b5eb1bdf0a4df256'
silent! let g:plugs['vim-fswitch'].commit = '94acdd8bc92458d3bf7e6557df8d93b533564491'
silent! let g:plugs['vim-snippets'].commit = '4e1d1456fd7d1d5d6cff256578a3e3bbeeb24e62'
silent! let g:plugs['vim-surround'].commit = 'baf89ad26488f6a7665d51b986f5c7ad2d22b30b'

PlugUpdate!

