" Generated by vim-plug
" 06-12-2022 07:02:59 PM
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['barbar.nvim'].commit = '9347ed838e0bfd8993d29eac1294f82b8e04c0c3'
silent! let g:plugs['coc.nvim'].commit = 'd436220bd70346221b590419fbe2f2564c4bbb7f'
silent! let g:plugs['filetype.nvim'].commit = 'b522628a45a17d58fc0073ffd64f9dc9530a8027'
silent! let g:plugs['gruvbox.nvim'].commit = '02a9182c66a8347d8328a32d58535dfb9785f6aa'
silent! let g:plugs['impatient.nvim'].commit = 'd3dd30ff0b811756e735eb9020609fa315bfbbcc'
silent! let g:plugs['indent-blankline.nvim'].commit = 'db7cbcb40cc00fc5d6074d7569fb37197705e7f6'
silent! let g:plugs['lualine.nvim'].commit = 'bfa0d99ba6f98d077dd91779841f1c88b7b5c165'
silent! let g:plugs['nerdcommenter'].commit = 'f8671f783baeb0739f556d9b6c440ae1767340d6'
silent! let g:plugs['nvim-colorizer.lua'].commit = '36c610a9717cc9ec426a07c8e6bf3b3abcb139d6'
silent! let g:plugs['nvim-dap'].commit = 'f0573ea26f29702ad9aa1546e102adb2f5b7ac3a'
silent! let g:plugs['nvim-dap-python'].commit = '27a0eff2bd3114269bb010d895b179e667e712bd'
silent! let g:plugs['nvim-dap-ui'].commit = '54365d2eb4cb9cfab0371306c6a76c913c5a67e3'
silent! let g:plugs['nvim-scrollview'].commit = 'b10165f3727f519566d69382c4a4830f16375910'
silent! let g:plugs['nvim-tree.lua'].commit = '829e9f68e10a998198e17bf5b348a6947f9d3c2e'
silent! let g:plugs['nvim-treesitter'].commit = 'ecb53631a849b7240b0200103369be2803f8805e'
silent! let g:plugs['nvim-treesitter-cpp-tools'].commit = '6c37990655440a77a114ad9a9e11e97959d0504d'
silent! let g:plugs['nvim-web-devicons'].commit = '189ad3790d57c548896a78522fd8b0d0fc11be31'
silent! let g:plugs['plenary.nvim'].commit = '4b7e52044bbb84242158d977a50c4cbcd85070c7'
silent! let g:plugs['telescope-coc.nvim'].commit = '0193fe529edd2cb61ccc020b492df76528f880fc'
silent! let g:plugs['telescope.nvim'].commit = 'b79cd6c88b3d96b0f49cb7d240807cd59b610cd8'
silent! let g:plugs['vim-fswitch'].commit = '94acdd8bc92458d3bf7e6557df8d93b533564491'
silent! let g:plugs['vim-snippets'].commit = '4e1d1456fd7d1d5d6cff256578a3e3bbeeb24e62'
silent! let g:plugs['vim-startuptime'].commit = '1acb5fa4aa29a24c36d559474b672cda9b9a9b6d'
silent! let g:plugs['vim-surround'].commit = 'baf89ad26488f6a7665d51b986f5c7ad2d22b30b'

PlugUpdate!

