require("plugins.plugin_keymaps")
require("plugins.gruvbox")
require("plugins.lualine")
require("plugins.nvim-tree")
require("plugins.barbar")
require("plugins.coc")
require("plugins.tree-sitter")
require("plugins.telescope")
require("plugins.dap-common")

require("plugins.copilot")
